# Nama aplikasi dengan perbaikan typo
name: application_jec_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# --- DEPENDENCIES ---
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # UI & Networking
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  
  # Location & Maps
  geolocator: ^12.0.0
  google_maps_flutter: ^2.7.0
  permission_handler: ^11.3.1
  
  # State Management & Utils
  provider: ^6.1.2
  intl: ^0.20.2
  url_launcher: ^6.3.0
  
  # Storage & Preferences - DIPERLUKAN UNTUK LANGUAGE SELECTOR
  shared_preferences: ^2.2.3
  
  # Animations & Effects
  confetti: ^0.7.0
  simple_animations: ^5.0.2
  
  # Media
  youtube_player_flutter: ^9.0.1
  table_calendar: ^3.1.2

  # PDF Viewer (untuk membuka file PDF)
  flutter_pdfview: ^1.3.2
  # File handling
  path_provider: ^2.1.1
  skeletonizer: ^2.1.0+1


# --- DEV DEPENDENCIES ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


# --- FLUTTER CONFIGURATION ---
flutter:
  uses-material-design: true

  # Path aset sudah dirapikan dan ditambahkan folder file
  assets:
    - assets/artikel/
    - assets/achievement/
    - assets/awards/
    - assets/carousel/
    - assets/cataract/
    - assets/dekorasi/
    - assets/docter/
    - assets/ebook/
    - assets/event/
    - assets/fasilitas/
    - assets/file/          # Folder baru untuk file E-Book
    - assets/icons/
    - assets/layanan/
    - assets/logo/
    - assets/map_styles/
    - assets/promo/
    - assets/sosial/
    - assets/testimoni/
    - assets/icons/iconsmenu/
    - assets/lang/id.json
    - assets/lang/en.json
    - assets/icons/iconsmenu/flacs.svg
    - assets/icons/iconsmenu/lasik.svg

